---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# trapgridR

<!-- badges: start -->
<!-- badges: end -->

trapgridR is an interace for the java program "TrapGrid" (ref) using R. Calling this program from R allows for multiple simulations to be run, and the results to be easily collated and summarised.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mattecologist/trapgridR")
```
## Example

```{r setup}
library(trapgridR)
```

There is a simple function to make a regular grid across a given area
```{r, fig.width=4, fig.height=4}
make_regular_grid("my_grid")
```


```{r}
model1 <- trapgridR(filepath="my_grid", nDays = 14, nFlies = 100, nSim=10, D=10^5)
```
```{r plot of simulation results, fig.width=5, fig.height=4}
library (ggplot2)
ggplot(model1$simRuns, aes(Day, 1-Cumulative.Escape.Probability, colour=SimRun, group=SimRun))+
  geom_line()+
  theme_dark()+
  scale_x_continuous(expand=c(0.01,0))+
  scale_y_continuous(expand=c(0,0.01))

```

```{r fig.width=5, fig.height=4}
ggplot (model1$flyLoc, aes(as.integer(X), as.integer(Y),  colour=as.integer(Simulation.Number)))+
  geom_point()+
  facet_wrap(.~as.integer(Day))+
  scale_colour_viridis_c()+
  theme_dark()

```
