---
title: "trapgrid-in-R"
author: "Matt Hill"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{trapgrid-in-R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The following is a demonstration of an interace with the java program "TrapGrid" (ref) using R. Calling this program from R allows for multiple simulations to be run, and the results to be easily collated and summarised.

```{r setup}
library(trapgridR)
```

There is a simple function to make a regular grid across a given area
```{r, fig.width=6, fig.height=6}
make_regular_grid("my_grid")
```


```{r}
model1 <- trapgridR(filepath="my_grid", nDays = 14, nFlies = 100, nSim=10, D=10^5)
```
```{r plot of simulation results, fig.width=7, fig.height=6}
library (ggplot2)
ggplot(model1$simRuns, aes(Day, 1-Cumulative.Escape.Probability, colour=SimRun, group=SimRun))+
  geom_line()+
  theme_dark()+
  scale_x_continuous(expand=c(0.01,0))+
  scale_y_continuous(expand=c(0,0.01))

```

```{r fig.width=7, fig.height=6}
# commented out until fly loc working in Java

# ggplot (model1$flyLoc, aes(as.integer(X), as.integer(Y),  colour=as.integer(Simulation.Number)))+
#   geom_point()+
#   facet_wrap(.~as.integer(Day))+
#   scale_colour_viridis_c()+
#   theme_dark()

```

Lets pretend the actual Orchard is an 800 x 800 m square with 10 random traps placed in it.

```{r}

traps <- data.frame()
for (i in 1:10){
  temp <- runif(2, 0, 800)
  traps <- rbind(traps, temp)
}
names (traps) <- c("Latitude", "Longitude")

plot (traps[,"Latitude"]~ traps[,"Longitude"])

```
```{r}
#Assign a lamba (trap attractiveness)
make_actual_grid(gridname="orchard_traps", traps, lambda = 0.005)
```

```{r}
outbreaks.data <- make_outbreak_file(traps=traps, in_orchard = FALSE,
                   outbreak_name = "outbreaks")
```

```{r}
model2 <- trapgridR("orchard_traps", nDays=28, nFlies=5, nSim=10, D=10^5, outbreaks = "outbreaks")
```

```{r}
outbreaks <- tidyr::separate(model2$simRuns, Outbreak.Location, into=c("X", "Y"), sep=",")[,c("X", "Y")]
outbreaks <- outbreaks[complete.cases(outbreaks),]
outbreaks$X <- as.numeric(gsub("\\(|\\)", "", outbreaks$X))
outbreaks$Y <- as.numeric(gsub("\\(|\\)", "", outbreaks$Y))
outbreaks <- unique(cbind(outbreaks$X, outbreaks$Y))
outbreaks <- sp::SpatialPoints(outbreaks[,1:2]) 
```

```{r}
cols <- viridis::viridis(3)
library (ggsci)
library (ggplot2)


ggplot (data=as.data.frame(outbreaks.data$traps_sp), aes(Latitude, Longitude)) +
  geom_point(size=2, shape=7)+
  geom_point(data=as.data.frame(outbreaks), aes(coords.x1, coords.x2), colour=cols[3], alpha=0.8)+
  geom_polygon(data=outbreaks.data$buffer_traps, aes(x=long, y=lat, group = group), colour=cols[2], fill=cols[2], alpha=0.45)+
  geom_polygon(data=outbreaks.data$orchard_buffer, aes(x=long, y=lat, group = group), alpha=0.2, fill=cols[1])+
  theme_minimal()+
  coord_equal()+
  xlab("X (m)")+
  ylab("Y (m)")+
  ggtitle(paste0("1/lambda: ",round(1/0.005,2), ", Outbreaks: ", round(raster::area(outbreaks.data$outbreak_buffer)/10000, 0)))


```

